sudo: required

before_script:
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
- helm init
# - npm install -g lerna

script:
# - curl -L https://raw.githubusercontent.com/cncf/k8s-conformance/master/sonobuoy-conformance.yaml | kubectl apply -f -
- kubectl cluster-info
- helm search ipfs
- helm install --name mini-ipfs stable/ipfs

# - helm install --name mini-kong stable/kong
# - sleep 60

# - minikube service --url mini-kong-kong-proxy
# - ./travis.sh

# sudo: required
# dist: trusty
# language: node_js

# cache:
#   directories:
#   - $HOME/.yarn-cache

# node_js:
#   - "8.4.0"

# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install software-properties-common -y -qq
#   - wget "https://dist.ipfs.io/go-ipfs/v0.4.9/go-ipfs_v0.4.9_linux-amd64.tar.gz" -O /tmp/ipfs.tar.gz
#   - pushd . && cd $HOME/bin && tar -xzvf /tmp/ipfs.tar.gz && popd
#   - export PATH="$HOME/bin/go-ipfs:$PATH"
#   - ipfs init
#   - ipfs daemon &
#   - sleep 5
#   - npm install -g yarn --cache-min 999999999 lerna ethereumjs-testrpc truffle
#   - testrpc >> /dev/null &

# install:
#   - lerna bootstrap
  
# script:
#   - ./travis.sh
